# Generated by Django 5.2.14 on 2026-06-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railagentapp', '0002_alter_passengerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=15, null=True),
        ),
    ]
