# Generated by Django 5.2.14 on 2026-06-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railagentapp', '0003_alter_passengerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='email',
            field=models.EmailField(default='hello', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
